package org.educoins.core.p2p.peers.remote;

import org.educoins.core.Block;
import org.educoins.core.utils.Sha256Hash;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.net.URI;
import java.util.Collection;

/**
 * The base class representing a remote note.
 * This interface should be implemented to exchange data with a specific node.
 * Created by typus on 11/3/15.
 */
public abstract class RemoteNode {
    protected Long id;
    protected URI iNetAddress;
    protected String pubkey;

    public RemoteNode() {
    }

    public RemoteNode(@NotNull Long id, @NotNull URI iNetAddress, @NotNull String pubkey) {
        this.id = id;
        this.iNetAddress = iNetAddress;
        this.pubkey = pubkey;
    }

    /**
     * Returns all {@link Block#getHeader()}s from the specific {@link RemoteNode}.
     *
     * @return All {@link Block#getHeader()}s the {@link RemoteNode} knows.
     * @throws IOException if the communication went wrong.
     */
    @NotNull
    public abstract Collection<Block> getHeaders() throws IOException;

    /**
     * Returns all {@link Block}s from the specific {@link RemoteNode}.
     *
     * @return All {@link Block}s the {@link RemoteNode} knows
     * @throws IOException if the communication went wrong.
     */
    @NotNull
    public abstract Collection<Block> getBlocks() throws IOException;

    /**
     * Returns a specific {@link Block} specified by {@link Block#hash()} from the specific {@link RemoteNode}.
     *
     * @param hash the {@link Sha256Hash} generated by {@link Block#hash()}}.
     * @return the {@link Block} or <code>null</code> if not found.
     * @throws IOException if the communication went wrong.
     */
    @Nullable
    public abstract Block getBlock(Sha256Hash hash) throws IOException;

    public String getPubkey() {
        return pubkey;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (iNetAddress != null ? iNetAddress.hashCode() : 0);
        result = 31 * result + (pubkey != null ? pubkey.hashCode() : 0);
        return result;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        RemoteNode node = (RemoteNode) o;

        return !(id != null ? !id.equals(node.id) : node.id != null)
                && !(iNetAddress != null ? !iNetAddress.equals(node.iNetAddress) : node.iNetAddress != null)
                && !(pubkey != null ? !pubkey.equals(node.pubkey) : node.pubkey != null);
    }
}
